FROM microsoft/dotnet:2.1-sdk

WORKDIR /src

COPY src/ src
COPY tests/ tests

WORKDIR /src/src/TwilioSdkStarterDotnetCore.Web

RUN dotnet restore && dotnet test ../../tests/TwilioSdkStarterDotnetCore.Tests/TwilioSdkStarterDotnetCore.Tests.csproj
